### PR TITLE
Updated package name - move to doctrine org

### PR DESCRIPTION
**Pull request by michalbundyra**
As discussed with @TomHAnderson there is a plan of moving that repository into doctrine org.

This PR changes the package name and update LICENSE.

### CODE REVIEW

**Comment by marcguyer** [comment]
Just wondering what is the status of this move? Is there a known release roadmap?

**Comment by webimpress** [comment]
@marcguyer 
Unfortunately I have no idea :(
I can't do that on my own, as I do not have permission to doctrine org.
I gave permission to @jwage to that repository and talked to him a while ago.

We just need to wait for his move...

**Comment by TomHAnderson** [comment]
There is a problem in the https://github.com/doctrine/dbal which affect the hydrator in DoctrineModule.  I'm having trouble gaining purchase with others but I think the scope of the problem and the types of changes required get lost in the conversation.

https://github.com/doctrine/dbal/pull/3291

As-is there is not a method for a custom field like DATETIME(6) to properly render themselves in a hydrator for hydration.  

I'm stuck on this issue and haven't made movement for some time.

**Comment by reinfi** [comment]
any news on this? This would really help to reduce depencendies.

**Comment by jwage** [comment]
I will take a look at this today.

**Comment by webimpress** [comment]
ping @jwage

**Pull request closed without merging**
